### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by gustavkarlsson** [carthago/odette4j#4]
Hi, I'm looking for a decent oftp client implementation for java and stumbled upon this project. What's the general status of it? Is it usable? What about stability?

**Comment by mgrossmann** [comment]
Hi, Gustav. This project is not in an usable state. It's in the very beginning. :) If you are searching for an usable library, search for accord oftp here on GitHub. This project seams to be dead, but is in an usable state i think. I use it to test again.

**Comment by gustavkarlsson** [comment]
Thanks. I'll look into it.
